### ISSUE TITLE
BLAS symbol not found with this configuration

### ISSUE THREAD

**Issue by Schroedingers0216** [eth-cscs/DLA-Future#1196]
My compilation command：
cmake -DDLAF_DIR=./DLA-Future-install -DDLAF_WITH_MKL=ON  -DMKL_ROOT=/public/software/compiler/intel-compiler/2021.3.0/mkl  -Dlapackpp_DIR=/public/software/OpenBLAS-0.3.21/install/lib  -DDLAF_WITH_SCALAPACK=ON -DDLAF_WITH_HIP=ON -DDLAF_BUILD_TESTING=ON -DDLAF_INSTALL_TESTS=ON -DDLAF_WITH_GPU=OFF  -DCMAKE_PREFIX_PATH=./DLA-Future/whip/build/install ..
error：
CMake Error at cmake/FindLAPACK.cmake:45 (message):
  BLAS symbol not found with this configuration
Call Stack (most recent call first):
  cmake/FindLAPACK.cmake:66 (_lapack_check_is_working)
  CMakeLists.txt:160 (find_package)

Which BLAS library should I use?

**Comment by msimberg** [comment]
The recommended way to install DLA-Future is through spack (https://spack.readthedocs.io/en/latest/). There's a brief overview on variants etc. in https://github.com/eth-cscs/DLA-Future/blob/master/BUILD.md#build-using-spack.

Any instructions on building manually may be out of date, and we don't guarantee that they'll be up to date. If you must build manually, there are some instructions on building manually in https://github.com/eth-cscs/DLA-Future/blob/master/BUILD.md#build-the-good-old-way and below. I highly recommend you don't do this unless you're packaging DLA-Future for a distribution.

<details><summary>Manual configuration/install</summary>

As for your CMake command, see comments below.

> -DDLAF_DIR=./DLA-Future-install

This is not a DLA-Future CMake variable. If you meant to specify where to install DLA-Future, see https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html#cmake-install-prefix.

> -DDLAF_WITH_MKL=ON

You didn't specify which version of DLA-Future you're building, but if you're building 0.6.0, this variable is meant for explicitly telling CMake that MKL is expected. In most cases you can leave this out and DLA-Future will detect it for you. You must then set the `LAPACK_LIBRARY` variable to include the include and link flags for MKL. If the flags are set incorrectly, DLA-Future will fail to find MKL.

> -DMKL_ROOT=/public/software/compiler/intel-compiler/2021.3.0/mkl

Since a few versions ago this is no longer taken into account.

> -Dlapackpp_DIR=/public/software/OpenBLAS-0.3.21/install/lib

This seems inconsistent. Why is lapackpp installed in the OpenBLAS directory and why is OpenBLAS being used with MKL?

> -DDLAF_WITH_SCALAPACK=ON

This is ok, but you must set `SCALAPACK_LIBRARY` similarly to `LAPACK_LIBRARY` for this to work.

> -DDLAF_WITH_HIP=ON

This is ok, but possibly not intended.

> -DDLAF_WITH_GPU=OFF

This is an internal variable and contradicts the HIP variable.

> -DDLAF_BUILD_TESTING=ON -DDLAF_INSTALL_TESTS=ON

You most likely don't want these if you're simply installing DLA-Future, but they don't hurt.

> -DCMAKE_PREFIX_PATH=./DLA-Future/whip/build/install

This is ok, but I highly recommend not installing libraries in the build directory.

Note that `LAPACK_LIBRARY` and `SCALAPACK_LIBRARY` will be renamed to `DLAF_LAPACK_LIBRARY` and `DLAF_SCALAPACK_LIBRARY` in the upcoming 0.7.0 release.
</details>

> Which BLAS library should I use?

That depends on the system you're running on. For most x86 systems Intel MKL is a good choice, including AMD systems. Note that the 2021 MKL is very outdated. We strongly recommend using the newer MKL shipped with oneAPI (https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl.html). Again, this is easiest to install through spack. On Nvidia Grace CPUs nvpl is typically fastest. OpenBLAS can also be a good option if no other BLAS implementation is available.

</detail>

**Comment by Schroedingers0216** [comment]
> The recommended way to install DLA-Future is through spack (https://spack.readthedocs.io/en/latest/). There's a brief overview on variants etc. in https://github.com/eth-cscs/DLA-Future/blob/master/BUILD.md#build-using-spack.
> 
> Any instructions on building manually may be out of date, and we don't guarantee that they'll be up to date. If you must build manually, there are some instructions on building manually in https://github.com/eth-cscs/DLA-Future/blob/master/BUILD.md#build-the-good-old-way and below. I highly recommend you don't do this unless you're packaging DLA-Future for a distribution.
> 
> Manual configuration/install
> > Which BLAS library should I use?
> 
> That depends on the system you're running on. For most x86 systems Intel MKL is a good choice, including AMD systems. Note that the 2021 MKL is very outdated. We strongly recommend using the newer MKL shipped with oneAPI (https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl.html). Again, this is easiest to install through spack. On Nvidia Grace CPUs nvpl is typically fastest. OpenBLAS can also be a good option if no other BLAS implementation is available.

If I use Intel MKL, what is my compilation command？

**Comment by msimberg** [comment]
> If I use Intel MKL, what is my compilation command？

Please see the "Manual configuration/install" section in my previous comment, though again, I don't recommend building DLA-Future this way. Please use https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-link-line-advisor.html to determine what flags to set for MKL. Unless you have other constraints you'll likely end up with something like
```
-I${MKLROOT}/include -L${MKLROOT}/lib -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl
```
DLA-Future does not require any particular flavour of MKL, though not all variants have been tested.

**Comment by rasolca** [comment]
Please also note that:
- all the required dependencies has to be installed manually and consistency in the dependency tree has to be guaranteed by the user,
- BLAS != blaspp,
- LAPACK != lapackpp

**Comment by Schroedingers0216** [comment]
sorry，Since I don't have a spack environment, I have to build from source code. I have set the MKL_ROOT and configured relevant parameters according to the documentation when running the commands. However, the result shows "BLAS symbol not found with this configuration". What modifications do I need to make to the compilation commands to successfully build it?


cmake -DDLAF_DIR=./DLA-Future-install -DDLAF_WITH_MKL=ON  -DMKL_ROOT=/public/software/compiler/intel-compiler/2021.3.0/mkl  -DDLAF_WITH_SCALAPACK=ON -DDLAF_WITH_HIP=ON -DDLAF_BUILD_TESTING=ON -DDLAF_INSTALL_TESTS=ON -DDLAF_WITH_GPU=OFF  -DCMAKE_PREFIX_PATH=./DLA-Future/whip/build/install ..
![image](https://github.com/user-attachments/assets/cd470983-fd68-49b1-89fd-357712403336)

**Comment by Schroedingers0216** [comment]
I have compiled and installed lapackpp and blaspp from source code, but there are still issues.


cmake -DDLAF_DIR=./DLA-Future-install -DDLAF_WITH_MKL=OFF  -DMKL_ROOT=/public/software/compiler/intel-compiler/2021.3.0/mkl -DDLAF_WITH_HIP=ON -DDLAF_BUILD_TESTING=ON -DDLAF_INSTALL_TESTS=ON -DDLAF_WITH_GPU=OFF -Dlapackpp_DIR=./DLA-Future/lapackpp/build/install -Dblaspp_DIR=./DLA-Future/blaspp/build/install  -DCMAKE_PREFIX_PATH=./DLA-Future/whip/build/install ..

**Comment by RMeli** [comment]
Hi @Schroedingers0216, have you seen the "Manual configuration/install" section in https://github.com/eth-cscs/DLA-Future/issues/1196#issuecomment-2382575437? The section is a drop-down one, you need to click on it to show it. 

Please have a look at the explanations in the "Manual configuration/install" section; your latest `cmake` commands still contains some of the issues discussed there.

**Comment by Schroedingers0216** [comment]
> Hi @Schroedingers0216, have you seen the "Manual configuration/install" section in [#1196 (comment)](https://github.com/eth-cscs/DLA-Future/issues/1196#issuecomment-2382575437)? The section is a drop-down one, you need to click on it to show it.
> 
> Please have a look at the explanations in the "Manual configuration/install" section; your latest `cmake` commands still contains some of the issues discussed there.

Indeed, I followed the build manual, and I have already configured Intel MKL. However, why do I encounter the error "BLAS symbol not found with this configuration"? Normally, it should be automatically detected.

**Comment by rasolca** [comment]
We disabled MKL auto detection because it was creating many problems. When different libraries links MKL, it is very easy to get inconsistencies and therefore problems.

You have to provide explicitly the include directory and the full link line given by https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-link-line-advisor.html. (see https://github.com/eth-cscs/DLA-Future/blob/master/cmake/FindDLAF_LAPACK.cmake#L19-L23)

Please make sure that the option you pick in the link line advisor are consistent with the the blaspp choices. Finally if you are using DLAF in an application which link MKL too, please make sure that all the MKL link lines are consistent, otherwise you might get weird performance or segfaults.

**Comment by Schroedingers0216** [comment]
I'm very sorry, but I encountered two issues while trying to install dla-future using Spack with the command: spack install dla-future +rocm amdgpu_target=gfx906 +scalapack ^[virtuals=blas,lapack,scalapack] intel-oneapi-mkl. The first issue is the failure of pika installation: I have set the library path for /rocm/comgr   

2 errors found in build log:
     10    -- CMake version: 3.30.5
     11    -- pika version: 0.27.0
     12    -- Nice threadlevel is disabled.
     13    -- Stack traces are enabled.
     14    -- The HIP compiler identification is Clang 15.0.0
     15    -- Detecting HIP compiler ABI info
  >> 16    CMake Error at /spack/opt/spack/linux-centos7-x86_64_v3/clang-15.0.0/cmake-3.30.5-z7da57towvdhh66y7hoexjp5cifqllbe/share/cmake-3.30/Modules/CMakeFindDependencyMacro.cma
           ke:76 (find_package):
     17      By not providing "Findamd_comgr.cmake" in CMAKE_MODULE_PATH this project
     18      has asked CMake to find a package configuration file provided by
     19      "amd_comgr", but CMake did not find one.
     20    
     21      Could not find a package configuration file provided by "amd_comgr" with
     22      any of the following names:

     ...

     31    Call Stack (most recent call first):
     32      /dtk-24.04.3/lib/cmake/hip-lang/hip-lang-config.cmake:88 (find_dependency)
     33      /spack/opt/spack/linux-centos7-x86_64_v3/clang-15.0.0/cmake-3.30.5-z7da57towvdhh66y7hoexjp5cifqllbe/share/cmake-3.30/Modules/CMakeHIPInformation.cmake:106 (find_packa
           ge)
     34      /tmp/root/spack-stage/spack-stage-pika-0.27.0-d3yeup7ikpuitj65yrir3lgjoeq3q5bn/spack-build-d3yeup7/CMakeFiles/CMakeScratch/TryCompile-7F4ioc/CMakeLists.txt:3 (project
           )
     35    
     36    
  >> 37    CMake Error at /spack/opt/spack/linux-centos7-x86_64_v3/clang-15.0.0/cmake-3.30.5-z7da57towvdhh66y7hoexjp5cifqllbe/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cm
           ake:74 (try_compile):
     38      Failed to configure test project build system.
     39    Call Stack (most recent call first):
     40      /spack/opt/spack/linux-centos7-x86_64_v3/clang-15.0.0/cmake-3.30.5-z7da57towvdhh66y7hoexjp5cifqllbe/share/cmake-3.30/Modules/CMakeTestHIPCompiler.cmake:32 (CMAKE_DETE
           RMINE_COMPILER_ABI)
     41      cmake/pika_setup_hip.cmake:28 (enable_language)
     42      CMakeLists.txt:904 (include)
     43    




1 error found in build log:
     35       -DBLAS_FORTRAN_LOWER                             no (didn't run: int mismatch, etc.)
     36       -DBLAS_FORTRAN_LOWER -DBLAS_ILP64                no (didn't run: int mismatch, etc.)
     37       -DBLAS_FORTRAN_UPPER                             no (didn't run: int mismatch, etc.)
     38       -DBLAS_FORTRAN_UPPER -DBLAS_ILP64                no (didn't run: int mismatch, etc.)
     39       BLAS library not found.
     40    
  >> 41    CMake Error at CMakeLists.txt:430 (message):
     42      BLAS++ requires a BLAS library and none was found.  Ensure that it is
     43      accessible in environment variables $CPATH, $LIBRARY_PATH, and
     44      $LD_LIBRARY_PATH.
     45    
     46    
     47    -- Configuring incomplete, errors occurred!

See build log for details:
  /tmp/root/spack-stage/spack-stage-blaspp-2024.10.26-uurb5zxxcijarwudor7pm32gnnomdezp/spack-build-out.txtand the second issue is the failure of blaspp installation.：



How should I resolve these problems? @RMeli @rasolca @haampie
