### ISSUE TITLE
Proposal: Split DLAF into `core` and `kernels`

### ISSUE THREAD

**Issue by teonnik** [eth-cscs/DLA-Future#226]
Since we introduced ETI, contrary to the initial goal, some of our incremental compile times have suffered. This is mostly due to `  factorization/mc.cpp` and `solver/mc.cpp`. For example, working on TSGEMM, if I modify the `index2d.h`, `matrix.h` or `tile.h` headers, I trigger recompilation for the `*mc.cpp` files too because they are part of the DLAF target and depend on the mentioned headers. As we add more and more kernels, the problem will become worse as we will have to compile all other kernels even if they aren't used or mentioned in the kernel we are working on. That is why I suggest we split DLAF into two parts: `core` and `kernels`. `kernels` contains `[factorization/solver]/mc.cpp` (and `tsgemm` in the future, etc) and their headers, core contains everything else (Matrix, MatrixView, Tile, Index2D, Size2D, etc : the fundamental types).

An outline for the proposed file structure could look like this:

core/
    |-- include/
    |-- src/
    |-- CMakeLists.txt

kernels/
   |-- include/
   |-- src/
   |-- CMakeLists.txt

We can expose two targets: dlaf.core and dlaf.kernels. Tests that need only link with dlaf.core will benefit greatly from incremental compile times.

Note that we don't have to change the code structure (i.e. namespace, names, etc), just the physical structure of the project.

What do you think?

**Comment by teonnik** [comment]
An alternative, more modest proposal is to keep the current project layout but still define two different CMake targets: `dlaf.core` and `dlaf.kernels` and link our tests / miniapps with them.

**Comment by rasolca** [comment]
I don't understand how the split solves the problem:
if you modify the core, and then you want to compile a test which involves one of the kernels, the full kernel library has to be recompiled too to be able to link the tests.

**Comment by teonnik** [comment]
> if you modify the core, and then you want to compile a test which involves one of the kernels, the full kernel library has to be recompiled too to be able to link the tests.

Yes, in that situation, there isn't any benefit, however in the following is:

1. A test that only depends on core
2. A miniapp that only depends on core  (this may be the case when prototyping a kernel)

**Comment by rasolca** [comment]
Ok, but in this case I would go for the light version (i.e. structure as it is now, multiple targets).
I would anyway still create the target dlaf with everything for external usage.
What about separating the kernels as well? This would help even when developing a kernel.
- dlaf.core
- dlaf.factorization
- dlaf....
@albestro What do you think?

**Comment by teonnik** [comment]
> Ok, but in this case I would go for the light version (i.e. structure as it is now, multiple targets).

Sure thing!

> I would anyway still create the target dlaf with everything for external usage.

Yes.

> What about separating the kernels as well? This would help even when developing a kernel.

I am in favour of that.

**Comment by albestro** [comment]
The strategy for addressing "incremental" build is splitting the problem: @teonnik proposal is a binary split, while @rasolca proposes a slightly more articulated one.

I like the idea of having a "global" helper target `dlaf` that groups all modules together.

About how many modules, it is a matter of how much modules are inter-connected.

- Having just `core` and `kernels`, as already said, won't help us much; `core` is by construction something on which approximately every other module will rely on, so a change in it will trigger the build of any other module. So, we are left with just another module and not so many benefit on incremental build side.
- By splitting more, we will have the `core` module, and a change in `factorization` would not trigger the build for `solvers` (and all dependent ones), since they should be disjointed.

I would more incline to support @rasolca proposal.

About folder structure, I think it would be more clear to reflect the CMake targets taxonomy also in the filesystem, but I think it would be the only benefit. On the other side, I don't see for the moment any reason to separate module like if they were completely separated/isolated projects. So, I'm not really sure it is worth changing the filesystem structure.
