### ISSUE TITLE
Work on subtiles

### ISSUE THREAD

**Issue by rasolca** [eth-cscs/DLA-Future#354]
When using the Panel #309 and in general when reusing a Tile as a workspace in an algorithm in some cases the tile sizes might mismatch. (E.g. the width of the last panel of a matrix might be less than the block size).

I can think about 3 ways to solve this problem:

1) Do nothing, and instead of Tile wrappers use Plain BLAS/LAPACK specifying the correct sizes.

2) The panel width is set at the beginning of the iteration (and sets the correct size to the tiles returned).

3) Provide a method to take a sub tile.

Details:

2) A Tile method for resizing is required. It should be private/protected and accessible only from the Panel (friend).
(We don't want users to mess with Tile sizes).
A panel method can be used to set the panel width at the beginning of the iteration (which sets the tile size correctly and stop the execution if a too large (compared to the allocated space) width is requested).
I don't see any complication using this method.

3) To implement this approach is more tricky:
3.1) One solution can be to modify the Tile to include extra information (i.e. current start index and current tile size).
Current index and size are used by the Tile to return the pointer and the size, while when the Tile destructor is called and therefore the tile sets itself in the promise, only the original size is used and the index and size are reset.
This approach is simple, but has two drawbacks:
- In a task the tile can only shrink (i.e. a task cannot work first only on the first half of the tile and then on the full tile)
- Const Tiles referenced from a shared future cannot use this approach, otherwise a race condition between different read operation might occour.

3.2) A sub-tile object which contains a reference to the Tile and the start index and size of the subtile.
The drawback of this approach is that the original Tile lifetime should be managed and guaranteed by the user and therefore the sub-tile can be used only within a task.

I think we should use both 2 and 3.2 for the following reasons:
- 3.2 allows any sub-tiling in tasks.
- The width of the panel is known at the beginning of each iteration, therefore with 2 it is not needed to take a sub-tile each time a panel tile is used.

@albestro @teonnik @msimberg @Sely85 Any comment is welcome.

**Comment by albestro** [comment]
Just to keep everyone up-to-date on this. We discussed with @rasolca about this and we thought about a possible alternative solution (I think @rasolca is going to check feasibility in the next weeks).

Just a few main points to show the general idea, details will come later.
- Use the same concept used in `MatrixView` where given a Future<Tile> from a Matrix, a "DAG loop" is created that it takes care of setting the promise of the Matrix according to the RO/RW access, when the DAG loop is over.
- Inside the "DAG loop" originated, there is the abstract concept of SubTile, but it should be possible to use the Tile (with some small internal change)
- From a Tile it is possible to create a set of SubTiles (a SubTile is an abstract concept, probably it will just appear as a classic Tile)
- Given a Future to a RO Tile, it will be possible to generate an unconstrained set of RO SubTiles (no race-condition since they are RO). These latter stores the shared_future of the original tile, so that until they exists, the original one is not "released" in the matrix.
- Given a Future to a RW Tile, it will be possible to generate a set of RW Tiles, but for keeping away race-conditions issues, these set has to be described so that SubTiles access disjoint sets of elements. Differently from the RO SubTiles, in order to unlock the original future, each one on destruction will set a promise and there will be a "collector" object (like in the MatrixView case) waiting for all the promises of the generated SubTiles to be set, when it will unlock the original one.

(@rasolca feel free to edit/add anything)
