### ISSUE TITLE
initialize/finalize RAII wrapper

### ISSUE THREAD

**Issue by msimberg** [eth-cscs/DLA-Future#411]
@albestro discovered a problem in the triangular solver miniapp, where we call `dlaf::finalize` explicitly at the end of `hpx_main`, but the `MatrixMirror` destructor tries to synchronize the matrices after `finalize` is called. This is is an error because the CUDA stream pool has been released by `finalize`.

I think we just need a simple RAII wrapper for finalize to make it easier to avoid these kind of problems. In the simplest case:

```
namespace dlaf {
struct initializer {
    initializer(int argc, char* argc[]) { initialize(argc, argv); }
    ~initializer() { finalize();
};
}
```

This ensures that resources are freed in the right order. Any objections or other ideas?

**Comment by albestro** [comment]
About the solution you are proposing, I think it may not really solve the problem but just shift it.

What we have usually is something like

```cpp
int foo() {
  dlaf::initialize();

  MatrixMirror m;

  dlaf::finalize();
  return hpx::finalize()
}
```

with the order for d'tors being
1. dlaf
2. hpx
3. matrix mirror

The problem is that we would like to have MatrixMirror being destroyed before all the other ones.

If we make our initializer RAII compliant, we would end up having something like
```cpp
int foo() {
  dlaf::initializer dlaf_init;

  MatrixMirror m;

  return hpx::finalize()
}
```

And at this point the d'tors order will be:
1. hpx
2. MatrixMirror
3. dlaf

where the original problem is improved with respect to dlaf, but now it has been moved to `hpx`.
