### ISSUE TITLE
Compiler Warnings

### ISSUE THREAD

**Issue by albestro** [eth-cscs/DLA-Future#51]
We should start using compiler warnings.

Topics:

- What set of warnings do we want to use?
- Manage different compilers options
- Should warning be set just for internal build (PRIVATE) or also as a usage constraint (PUBLIC)?

**Comment by albestro** [comment]
**What set of warnings do we want to use?**

This seems a good reference https://github.com/lefticus/cppbestpractices/blob/master/02-Use_the_Tools_Available.md#compilers

**Comment by albestro** [comment]
**Manage different compilers options**

Each compiler may have a different number of warning options and also the common one may have different names, so they should be managed in the CMake build system.

Another point where compiler differences management can be needed is in source code where it is necessary to disable specific options for a particular section (e.g. MPI header wrapper).

**Comment by albestro** [comment]
**Should warning be set just for internal build (PRIVATE) or also as a usage constraint (PUBLIC)?**

For sure we should use warnings for building our library, but do we want to force this "constraint" also to dependant projects?

Thinking about the "non-restrictive" option. The header-only part of the library, being built from the dependant project, would not generate warnings. But this is also true for the entire public API, e.g. an integer passed to our library would not be checked for overflow/narrowing/conversion.

**Comment by rasolca** [comment]
I suggest `-Wall -Wextra -Wnon-virtual-dtor -Wunused -Woverloaded-virtual -Wconversion -pedantic-errors`

`-Werror` should not be used since it may prevent the library to build on compilers we do not test. The flag may be added in the jenkins scripts.

They should be `PRIVATE`. The header only part generates warnings when tests are compiled (therefore we can check if the library is warning free). Moreover we cannot force warnings on an external project.

For external libraries the keyword `SYSTEM` should be used when adding include paths to disable warnings.
https://cmake.org/cmake/help/v3.0/command/target_include_directories.html?highlight=target_include_directory

**Comment by albestro** [comment]
Good point for `-Werror`, I will add it just in the CI.

I agree with you in keeping the warnings internally for the library. Anyway, it is worth pointing out that:

- If an external project uses our project in the CMake way, we could impose our set of warnings;
- If we want to check for warnings also the header-only part of the library, we have to impose the warnings not just on the library target, but also onto tests (on each single test target or globally).

About disabling warnings for external libraries, I already wrote my thoughts in [this comment](https://github.com/eth-cscs/DLA-Future/pull/49#discussion_r329476277). Summarizing it, I think that `SYSTEM` is just a workaround for having the wanted behavior, but I may agree that having a wrapper for the header may be a bit cumbersome in some cases.

**Comment by rasolca** [comment]
SYSTEM can be used with existing targets as well. (https://stackoverflow.com/questions/52135983/cmake-target-link-libraries-include-as-system-to-suppress-compiler-warnings)
Anyway we should first decide which set of warning to use and then see what is needed.

There also a drowback with the current method: if an external project includes MPI before our library. All MPI warnings will not be suppressed.

- External projects may need a different set of warnings because of other libraries or old pieces of code.
- As said in the previous comment, we test our interface (header only included) and therefore we check everything for warning. It is responsibility of the user to check is own code for warning.

**Comment by albestro** [comment]
I found this [resource](https://foonathan.net/2018/10/cmake-warnings/) which seems to address all the doubts/problems we discussed earlier.

**Comment by albestro** [comment]
Trying to summarize the problem we have.

Our target is to enable warnings for checking our own library, its sources and header files. We do not want to enforce checkings either on dependencies (and we don't want to see them) or on dependent code.

Our library is made of both:
- sources that generate the binary `libDLAF` and
- a header-only part of the library.

The former ones can be checked by just adding the `PRIVATE` specifier for the warning flags through `target_compiler_options`.

For what concerns the latter ones, they are compiled by user-code, so on our side, they can just be checked by:
- internal applications (e.g. mini-app),
- tests
- even internal libraries (e.g. pre-built header-only library for a specific set of types).

But, since we are talking of user code, the flags are not propagated by the library, and we have to add them manually for each "internal user code".

The other part of the problem is how to manage the warnings on dependencies. In fact, we could add the `SYSTEM` specifier in `target_include_directories` that turns off the warnings. This is possible just with CMake find-packages that follow the old-style, i.e. providing `*_LIBRARIES` and `*_INCLUDE_DIRS` variables. In fact, if a library provides a CMake target, we should find a way to "wrap" or "modify" the target itself (in case the library does not manage correctly the warnings like we are going to do with the `PRIVATE` specifier).

**Comment by albestro** [comment]
Update about how to manage warnings for external libraries that have CMake targets (see last section of the previous paragraph).

https://cmake.org/cmake/help/v3.13/prop_tgt/NO_SYSTEM_FROM_IMPORTED.html

For imported target, CMake by default uses the `SYSTEM` specifier. So there should not be any problem about warnings in external projects that uses Modern CMake style.

At least with GCC and CLANG, I don't know with other compilers (in terms of what they do with the SYSTEM specifier and if they have an equivalent of `-isystem` for hiding warnings).

@rasolca are GCC and CLANG the only compilers we want to support?
