### ISSUE TITLE
Update `selectGeneric`, `select`, `selectRead` to use sender access

### ISSUE THREAD

**Issue by msimberg** [eth-cscs/DLA-Future#605]
They currently use `operator()` and `read` on `Matrix` instead of the sender equivalents. Updating this to use the sender versions means that one can't anymore query whether a sender is "ready" or not. Some tests rely on this functionality. It's convenient for testing to sanity check if tile senders/futures are ready or not, but it's not clear if there's are use cases outside of testing and the functionality should be kept in some form. Alternatively, can the tests be refactored not to rely on `is_ready`?

Part of #468. #564 is also related since it added helpers that look like `select` and `selectRead` but use the sender accessors: https://github.com/eth-cscs/DLA-Future/blob/9dd8678478581f3dd261fb1bb45bc6e20a22e8db/include/dlaf/util_matrix.h#L390-L410. When updating `select*` the `collect*` helpers should be removed.

**Comment by albestro** [comment]
Trying to highlight main points of the problem blocking from switching to senders.

`test_matrix` and `test_matrix_view`, among other things, test if the tile "pipeline" mechanism works correctly by holding/releasing future<Tile> in a controlled way.

The main idea is that the test gets a specific sequence of `future<Tile>`, building up a DAG of dependencies, and step by step by releasing "one-by-one" the dependencies in the aforementioned sequence, it verifies that the DAG status is what is supposed to be (future is ready or not).

The tile mechanism is planned to be redesigned and rethought. However, if the general behaviour will still be valid, we can think about a possible solution already starting from now.

The more trivially and basic solution would be to implement something along the lines of what we did for `test_transfor_mpi`

https://github.com/eth-cscs/DLA-Future/blob/2258862a09350d0944add52eaeac626ec35b96ad/test/unit/communication/test_transform_mpi.cpp#L85-L92

It is not exactly the same behaviour, but probably is compatible with what we would like to test. We may try to think about something smarter, since in this case we would try to replicate the future mechanism with senders, requiring to keep the "status" of the sender in an atomic variable.

**Comment by msimberg** [comment]
This was done in #766.
