### ISSUE TITLE
FindMKL improvements

### ISSUE THREAD

**Issue by msimberg** [eth-cscs/DLA-Future#626]
Related to #622, @mtaillefumier also found that DLA-Future's FindMKL could not find the expected MKL libraries, whereas CP2K's (i.e. @mtaillefumier's CMake version of CP2K) could find it. We should investigate the reason for this difference and potentially update `FindMKL.cmake`.

@mtaillefumier could I ask you to add your `FindMKL.cmake` in some form to this issue?

This should also namespace the targets with `DLAF::`.

**Comment by mtaillefumier** [comment]
you can find it here https://github.com/mtaillefumier/cp2k/blob/cmake_v5/cmake/FindMKL.cmake. I basically used theodor mkl and added some more so that MKL::blas MKL::scalapack etc returns the proper things.

**Comment by albestro** [comment]
It seems this is something strictly related to our custom CMake module for FindMKL, that will get deprecated with #1073 and in the near future we will hopefully completely remove from the repo.

For this reason, I'm going to close this issue since with #1073 the preferred MKL provider is oneMKL that does not use anymore our custom CMake module. Feel free to reopen this issue in case you address the same problem.
