### ISSUE TITLE
`whenAllLift` considered dangerous

### ISSUE THREAD

**Issue by msimberg** [eth-cscs/DLA-Future#711]
I thought initially that `whenAllLift` would be a good idea, but thanks to an issue reported by @albestro I'm not so sure anymore.

Consider the following:
```
whenAllLift(select(mat, ...), ...)
```
This will compile, but the semantics are wrong. The code should read:
```
whenAllLift(when_all_vector(select(mat, ...), ...)
```
because `select` returns a vector of futures (i.e. senders).

Luckily this is not (as far as I can tell so far) not a correctness issue, because futures will block on `get` if the future is not ready, as they could be in the wrong version. However, it may be a performance issue, becase futures will block on `get` if the future is not...

There is some value in using `whenAllLift` in generic contexts, but I'm not sure it's worth the risk of mistakes like above.

Finally, this is problem that will automatically go away when there are no senders that send themselves (like there is now with futures sending themselves with `keep_future`).

How do you feel about not having `whenAllLift` and having to be explicit about wrapping plain values as senders? It would mean adding a whole bunch of `just`s in many places. I'm unsure exactly how extensive this change would need to be, so if it would help you judge the change I can make a draft PR with some (or all) `whenAllLift`s removed.

**Comment by albestro** [comment]
If this problem about `whenAllLift` exists just because of this "mixed state" between futures and senders, I think we might have to pay more attention and wait until we would have just a full sender-based implementation.

On the other hand, it is nice having `whenAllLift` saving from adding a lot of `just`, but it can be more transparent without it. I'm thinking about communication scheduling function where we pass `CommSender` which gets internally lifted if needed.

I look forward to other opinions, and if someone can raise a use-case which can help us opting for one solution or the other.

At the moment, I would say that we have an "against" (having it) use-case, but that might be eventually turned in "for" when the implementation will be "future-free", even if they will continue to exists (so danger is potentially always behind the corner).

**Comment by msimberg** [comment]
> If this problem about `whenAllLift` exists just because of this "mixed state" between futures and senders, I think we might have to pay more attention and wait until we would have just a full sender-based implementation.
> 
> On the other hand, it is nice having `whenAllLift` saving from adding a lot of `just`, but it can be more transparent without it. I'm thinking about communication scheduling function where we pass `CommSender` which gets internally lifted if needed.
> 
> I look forward to other opinions, and if someone can raise a use-case which can help us opting for one solution or the other.
> 
> At the moment, I would say that we have an "against" (having it) use-case, but that might be eventually turned in "for" when the implementation will be "future-free", even if they will continue to exists (so danger is potentially always behind the corner).

Fully agree, that's a good summary. At least we're currently aware of the danger and can keep an eye out for it (like with `keep_future`/`keepFuture`).

**Comment by msimberg** [comment]
I think we can close this now. Futures are no longer around, and it would be quite an obvious mistake if one accidentally wraps a vector of senders in `just` on the receiving end.
