### ISSUE TITLE
Warnings in GitHub Actions due to deprecations

### ISSUE THREAD

**Issue by albestro** [eth-cscs/DLA-Future#775]
By looking at the summary of a random action, it is possible to see this warnings

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/9337627/211860544-3a15dec5-73cc-4dd0-a370-f32263210a36.png">

From a quick check it seems triggered by `javascript-action` for which an updated version does not exist (?!).

**Comment by msimberg** [comment]
I think enabling dependabot would make sense for this. With that actions would be updated (semi)automatically if there's a new version and we wouldn't really need to worry about this warning because we'd be notified once there is a new version.

Are there any objections to enabling dependabot? In pika it's enabled by this file: https://github.com/pika-org/pika/blob/main/.github/dependabot.yml.
