### ISSUE TITLE
Refactoring snake_case

### ISSUE THREAD

**Issue by rasolca** [eth-cscs/DLA-Future#940]
Main algorithms should use `snake_case` names

**Comment by albestro** [comment]
Following up the discussion in https://github.com/eth-cscs/DLA-Future/pull/942#pullrequestreview-1537175233, it might be a good idea to continue here.

Let me report here some initial considerations:
1. we might want to have algorithm names that are self explicative without needing any "namespace context" (e.g. `tridiagonal_solver` and not `eigensolver::tridiagonal`, `multiplication::general` -> `gemm`)
2. we don't want long names: we can opt for shorting words (e.g. `backtransform` -> `bt`, but even more "aggressively" with `reduction_to_band` -> `red_to_band`)
3. namespace might not weigh much in the name length, since we can use `using dlaf::eigensolver`...but just if 1 is ensured, otherwise it (partially) becomes part of the algorithm name.
4. Another thing I would add is that probably the mapping between namespace and folder structure shouldn't be a constraint. We might keep the folder structure but, going all-in, algorithms might go all under `dlaf::algorithms` (or something like that). Again, if 1 is ensured.

**Comment by msimberg** [comment]
https://wg21.link/p1673 may also be useful for inspiration. Unfortunately it only covers blas, but it may be a start.

**Comment by rasolca** [comment]
An idea might be:
namespaces:
```
general
symmetric
hermitian
tridiagonal
triangular
positivdefinite
```
and then the name is the operation.
As `tridiagonal::matrix_matrix_multiplication` has different arguments from `symmetric::matrix_matrix_multiplication` and others it shouldn't be a problem.

My concern is about the directory structure, but if, as said by @albestro, we can decouple it, this option returns on the table.
